### ISSUE TITLE
[1.18.2] 建议：给调料增添获取方式

### ISSUE THREAD

**Issue by wumengzhixing** [SihenZhang/SimpleBBQ#2]
作者你好，可以考虑出下辣椒、孜然、花椒的种子以及种植相关的么？主要是那些调料只能交易，没有额外的获取方式，这样导致比较依赖于村民。

**Comment by SihenZhang** [comment]
这个mod设计的初衷就是为了一切从简，我们不希望添加太多离题的内容，作物就是其中之一。考虑到添加作物的形式在各类食物mod中太过常见，我们也认为这稍显无趣了，所以我们最终选择了村民作为调料的获取途径。

不过你提到的调料太过依赖村民确实是个问题，我们可能会考虑在地牢中加入一些调料包。

---
This mod was designed to keep everything simple, so we didn't want to add too much off-topic content, and crops were one of them. Considering that adding crops is too common in all kinds of food mods, we also thought it was a little boring, so we ended up choosing villagers as the way to get seasoning.

But your mention of relying too much on villagers for seasoning is a real problem, and we may consider adding some seasoning packs to the dungeon.
